[package]
name = "cni"
version = "0.1.0"
edition = "2024"
# version.workspace = true
# authors.workspace = true

[dependencies]
serde_json = "1.0"
my-workspace-hack = { version = "0.1", path = "../my-workspace-hack" }